apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: external-dns
  chart:
    git: git@github.com:benjh33/gitops-helm-workshop
    ref: master
    path: cluster/charts/external-dns
