---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:benjh33/gitops-helm-workshop
    ref: master
    path: cluster/charts/podinfo
  values:
    replicaCount: 2
    image:
      repository: stefanprodan/podinfo
      tag: 3.1.2
    service:
      enabled: false
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        external-dns.alpha.kubernetes.io/alias: "true"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:9898;
          proxy_hide_header l5d-remote-ip;
          proxy_hide_header l5d-server-id;
      path: /
      hosts:
      - podinfo.bjh.zimcore.io
